# Generated by Django 5.0.2 on 2024-03-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligas', '0002_alter_partit_unique_together_partit_detalls_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lliga',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='lliga',
            name='temporada',
        ),
        migrations.AlterField(
            model_name='equip',
            name='lligues',
            field=models.ManyToManyField(to='ligas.lliga'),
        ),
    ]
